[default.probe]
usb_vid = "1366"
usb_pid = "1015"
protocol = "Swd"
speed = 4000

[default.flashing]
enabled = true
restore_unwritten_bytes = false
halt_afterwards = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "nRF52840_xxAA"
connect_under_reset = false

[default.rtt]
enabled = true
up_mode = "NoBlockSkip"
control_block_address = 0x20037660  # Updated to match new _SEGGER_RTT
channels = [
    { up = 0, name = "defmt", format = "Defmt" },
]