[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Target for nRF52840 (Cortex-M4F with FPU)
runner = "probe-rs run --chip nRF52840_xxAA"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
# Default target for nRF52840
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"

[alias]
# Convenient aliases for common tasks
rb = "run --bin"
rrb = "run --release --bin"